# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
 
  check:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          separator: ","
          files: |
            *.yaml
          files_ignore: |
            *.yml

    outputs:
      is_modified: ${{ steps.changed-files.outputs.any_changed }}
      modified_yamls: ${{ steps.changed-files.outputs.modified_files }}
      
  build:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ needs.check.outputs.modified_yamls }}

    steps:
      - name: Run step if any of the listed files above change
        run: |
          PROJECT_NAME=$(yq .project.name ${{ matrix.file }})
          VERSION=$(yq .project.version ${{ matrix.file }})
          REPOSITORY=$(yq .project.repository ${{ matrix.file }})
          TAG=ghcr.io/qraft-technologies/$PROJECT_NAME:$VERSION
          
          git clone $REPOSITORY ./$PROJECT_NAME
          docker build . --build-arg PROJECT_PATH=./$PROJECT_NAME
          docker push $TAG
          
            
